# Generated by Django 3.2.2 on 2021-05-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True #Al ser migration inicial, mantiene valor de True

    dependencies = [
    ]

#id de modelo: identificador para saber a quien llamar y hacer consultas a la database
    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicacion')),
                ('ingredientes', models.CharField(max_length=100)),
                
            ],
        ),
    ]
