# Generated by Django 3.2.2 on 2021-05-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
