# Generated by Django 3.2.2 on 2021-05-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Check', '0002_receta_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
