# Generated by Django 3.2.2 on 2021-05-12 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Check', '0004_auto_20210511_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_modificacion',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='origen',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
