# Generated by Django 3.2.2 on 2021-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Check', '0006_alter_receta_fecha_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion', models.IntegerField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('contraseña_cliente', models.CharField(max_length=20)),
                ('fecha_creacion_cliente', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to=None)),
            ],
        ),
    ]
