# Generated by Django 3.2.2 on 2021-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Check', '0007_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion_cliente',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
