# Generated by Django 3.2.2 on 2021-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Check', '0008_auto_20210512_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='segundo_apellido_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
